# Travis-CI Build for Hangfire.Autofac
# see travis-ci.org for details

sudo: required
dist: trusty
dotnet: 2.0.3
mono: none

language: csharp

os: 
  - linux
  - osx

script:
    travis_retry dotnet restore --disable-parallel;
    dotnet test tests/Hangfire.Autofac.Tests/Hangfire.Autofac.Tests.csproj -c Release -f netcoreapp2.0;
