# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/hangfire-autofac

os: Visual Studio 2017

version: 2.3.0-build-0{build}

pull_requests:
  do_not_increment_build_number: true

build_script:
  - powershell .\build.ps1 -Target Pack

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\*.nupkg'
  - path: 'build\*.zip'
  
deploy:
  - provider: GitHub
    auth_token:
      secure: Kx+tJBMfq/OK7sMpvQDdigFOIIfzYkVmIHxNQetanQdIA5Mb8zm/VhAkrId4x5zW
    artifact: /.*\.zip/
    draft: true
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    api_key: 
      secure: 8BQmcR1hP9MoxvrmXJKMtlRyX6LI36H9ZTU8fSEetvzMGCl1PUlXKZRUGq+GVMja
    on:
      appveyor_repo_tag: true
